title: Código Pirata-Blog
description: "Nos computadores desde 1998"
author:
  name: "Paulo"
  email: "example@example.org"
  url: "https://paullomarttins.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

timezone: "America/Sao_Paulo"
locale: "pt_BR"
lang: "pt"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "p.mtx"
year : {{ currentyear }}
